global:
  pattern: my-vp-fork
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  configdemosecret:
    key: secret/data/global/config-demo-deloitte
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
